# Generated by Django 4.1.5 on 2023-01-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabricationOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabrication_order', models.IntegerField(max_length=10)),
                ('reference', models.CharField(max_length=50)),
                ('article', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(max_length=1000)),
            ],
        ),
    ]
